name: Trigger auto deployment for raks-demo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/raks-demo-AutoDeployTrigger-3ead1ec8-fa30-4b30-b1d6-59e53cfe1e72.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RAKSDEMO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RAKSDEMO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RAKSDEMO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.RAKSDEMO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RAKSDEMO_REGISTRY_PASSWORD }}
          containerAppName: raks-demo
          resourceGroup: DefaultResourceGroup-CCAN
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


